### ISSUE TITLE
Error: prompt is not defined (in replit)

### ISSUE THREAD

**Issue by if1eight0sty** [CodeWithHarry/ultimate-js-course-youtube#2]
I am following along with you, in the video 7 (conditionals), my code is:
`const name = prompt("Enter you name")`
this is giving me the above error: `prompt is not defined`
i have setup the node js repl. what can be the reasons?

**Comment by Ashwin7003** [comment]
add this line before using prompt statement-
const prompt = require("prompt-sync")();

**Comment by if1eight0sty** [comment]
@Ashwin7003 thanks
